// <auto-generated />
using Aplicada2doParcial.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Aplicada2doParcial.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20200311225406_Secundaria")]
    partial class Secundaria
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Aplicada2doParcial.Models.Casos", b =>
                {
                    b.Property<int>("CasoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LlamadaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Problema")
                        .HasColumnType("TEXT");

                    b.Property<string>("Solucion")
                        .HasColumnType("TEXT");

                    b.HasKey("CasoId");

                    b.HasIndex("LlamadaId");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("Aplicada2doParcial.Models.Llamadas", b =>
                {
                    b.Property<int>("LlamadaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(150);

                    b.HasKey("LlamadaId");

                    b.ToTable("Llamadas");
                });

            modelBuilder.Entity("Aplicada2doParcial.Models.Casos", b =>
                {
                    b.HasOne("Aplicada2doParcial.Models.Llamadas", null)
                        .WithMany("Casos")
                        .HasForeignKey("LlamadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
